You are given a 0-indexed array nums and an integer target.

A 0-indexed array infinite_nums is generated by infinitely appending the elements of nums to itself.

Return the length of the shortest subarray of the array infinite_nums with a sum equal to target. If there is no such subarray return -1.


# Solution
# Circular array type question but the catch is the infinite part where I needed help with, basically
# the idea is that for nums array what is the sum, take that sum, if target > sum it means that
# more then one nums array is needed and to find that is target // sum and by doing that our new target
# is target %= total if target is 28 our sum is 24 it means we need to find a subarray of sum of 4
# then add the original length of the subarray

# TC:O(2N)
# SC:O(1)

class Solution:
    def minSizeSubarray(self, nums: List[int], target: int) -> int:
        N = len(nums)
        total = sum(nums)
        k = target // total
        target %= total
        INF = 10 ** 20
        left = 0
        res = INF
        curr = 0
        for right in range(N * 2):
            x = nums[right % N]
            curr += x
            while curr >= target:
                if curr == target:
                    res = min(res,right - left + 1)
                curr -= nums[left % N]
                left += 1
        return k * N + res if res != INF else -1
